In [4]:
import numpy

world_alcohol =numpy.genfromtxt('world_alcool.txt',delimiter=',',dtype=str)
print(type(world_alcohol))
print(world_alcohol)
print(help(numpy.genfromtxt))

<class 'numpy.ndarray'>
[['1989' 'jiaojiang' 'lihuimin']
 ['1990' 'jiaojiang' 'lihuicong']]
Help on function genfromtxt in module numpy.lib.npyio:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is `.gz` or `.bz2`, the file is first decomp

In [8]:
vector = numpy.array([5,10,15,20])
matrix= numpy.array([[5,10,15],[20,25,30],[35,40,45]])
print(vector)
print(matrix)

[ 5 10 15 20]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [10]:
vector = numpy.array([1,2,3,4])
print(vector.shape)

matrix= numpy.array([[5,10,15],[20,25,30]])
print(matrix.shape)

(4,)
(2, 3)


In [14]:
import numpy

numbers=numpy.array([1,2,3,4.])
print(numbers)
numbers.dtype

[1. 2. 3. 4.]


dtype('float64')

In [17]:
world_alcohol

array([['1989', 'jiaojiang', 'lihuimin'],
       ['1990', 'jiaojiang', 'lihuicong']], dtype='<U9')

In [24]:
uruguay_other=world_alcohol[0,2]
third_country=world_alcohol[1,1]
print(uruguay_other)
print(third_country)

lihuimin
jiaojiang


In [25]:
vector = numpy.array([1,2,3,4])
print(vector[0:3])

[1 2 3]


In [26]:
print(world_alcohol[:,1])

['jiaojiang' 'jiaojiang']


In [28]:
print(world_alcohol[:,0:2])

[['1989' 'jiaojiang']
 ['1990' 'jiaojiang']]


In [29]:
print(world_alcohol[1:2,0:2])

[['1990' 'jiaojiang']]


In [30]:
vector = numpy.array([5,10,15,20])
vector ==10

array([False,  True, False, False])

In [31]:
matrix = numpy.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
matrix == 25

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [33]:
vector = numpy.array([5,10,15,20])
equal_to_ten = (vector ==10)
print(equal_to_ten)
print(vector[equal_to_ten])

[False  True False False]
[10]


In [34]:
matrix = numpy.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
second_colum_25 = (matrix[:,1] == 25)
print(second_colum_25)
print(matrix[second_colum_25,:])

[False  True False]
[[20 25 30]]


In [35]:
vector = numpy.array([5,10,15,20])
equal_to_ten_and_five = (vector ==10) & (vector ==5)
print(equal_to_ten_and_five)

[False False False False]


In [36]:
vector = numpy.array([5,10,15,20])
equal_to_ten_or_five = (vector ==10) | (vector ==5)
print(equal_to_ten_or_five)

[ True  True False False]


In [37]:
vector = numpy.array(['1','2','3'])
print(vector.dtype)
print(vector)
vector = vector.astype(float)
print(vector.dtype)
print(vector)

<U1
['1' '2' '3']
float64
[1. 2. 3.]


In [39]:
vector = numpy.array([5,10,15,20])
vector.min()

5

In [43]:
matrix = numpy.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])

a=matrix.sum(axis=1)  #对行进行求值
b=matrix.sum(axis=0)  #对列进行求值
print(a,b)

[ 30  75 120] [60 75 90]


In [44]:
import numpy as np
print(np.arange(15))
a=np.arange(15).reshape(3,5)
a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
a.shape

(3, 5)

In [46]:
a.ndim

2

In [48]:
a.dtype
a.dtype.name

'int64'

In [49]:
a.size

15

In [50]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [52]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [53]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [54]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [56]:
np.random.random((2,3))

array([[0.51930298, 0.1256625 , 0.97942232],
       [0.94269486, 0.65545364, 0.03925575]])

In [57]:
from numpy import pi

np.linspace(0,2*pi,100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [60]:
np.arange(0,2*pi,100)

array([0.])

In [61]:
np.sin(np.linspace(0,2*pi,100))

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [64]:
a=np.arange(10,30,5)
b=np.arange(4)
print(a,b)
c=a-b
print(c)
c=c-1
print(c)
d=b**2
print(d)
print(a<20)

[10 15 20 25] [0 1 2 3]
[10 14 18 22]
[ 9 13 17 21]
[0 1 4 9]
[ True  True False False]


In [65]:
A = np.array([[1,1],
              [0,1]])
B = np.array([[2,0],
              [3,4]])
print(A)
print('------------')
print(B)
print('------------')
print(A*B)
print('------------')
print(A.dot(B))
print('------------')
print(np.dot(A,B))

[[1 1]
 [0 1]]
------------
[[2 0]
 [3 4]]
------------
[[2 0]
 [0 4]]
------------
[[5 4]
 [3 4]]
------------
[[5 4]
 [3 4]]


In [66]:
import numpy as np
B = np.arange(3)
print(B)
print(np.exp(B))
print(np.sqrt(B))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


In [75]:
a = np.floor(10*np.random.random((3,4)))
print(a)
print("---------------")
print(a.ravel())
print("---------------")
a.shape=(6,2)
print(a)
print(a.T)

b=a.reshape(3,-1)   #-1 自动计算列
print(b)

[[2. 0. 0. 1.]
 [5. 8. 8. 2.]
 [0. 5. 3. 5.]]
---------------
[2. 0. 0. 1. 5. 8. 8. 2. 0. 5. 3. 5.]
---------------
[[2. 0.]
 [0. 1.]
 [5. 8.]
 [8. 2.]
 [0. 5.]
 [3. 5.]]
[[2. 0. 5. 8. 0. 3.]
 [0. 1. 8. 2. 5. 5.]]
[[2. 0. 0. 1.]
 [5. 8. 8. 2.]
 [0. 5. 3. 5.]]


In [79]:
import numpy as np
a= np.floor(10*np.random.random((2,3)))
b= np.floor(10*np.random.random((2,3)))
print(a)
print("------------")
print(b)
print("------------")
print(np.hstack((a,b)))
print("------------")
print(np.vstack((a,b)))

[[5. 3. 7.]
 [6. 4. 4.]]
------------
[[8. 3. 5.]
 [1. 4. 7.]]
------------
[[5. 3. 7. 8. 3. 5.]
 [6. 4. 4. 1. 4. 7.]]
------------
[[5. 3. 7.]
 [6. 4. 4.]
 [8. 3. 5.]
 [1. 4. 7.]]


In [85]:
a= np.floor(10*np.random.random((2,12)))
print(a)
print("------------")
print(np.hsplit(a,3))
print("------------")
print(np.vsplit(a.T,2))
print("------------")
print(np.hsplit(a,(3,4)))

[[0. 4. 5. 3. 9. 0. 1. 8. 9. 0. 7. 7.]
 [3. 9. 0. 7. 9. 0. 9. 5. 3. 5. 5. 3.]]
------------
[array([[0., 4., 5., 3.],
       [3., 9., 0., 7.]]), array([[9., 0., 1., 8.],
       [9., 0., 9., 5.]]), array([[9., 0., 7., 7.],
       [3., 5., 5., 3.]])]
------------
[array([[0., 3.],
       [4., 9.],
       [5., 0.],
       [3., 7.],
       [9., 9.],
       [0., 0.]]), array([[1., 9.],
       [8., 5.],
       [9., 3.],
       [0., 5.],
       [7., 5.],
       [7., 3.]])]
------------
[array([[0., 4., 5.],
       [3., 9., 0.]]), array([[3.],
       [7.]]), array([[9., 0., 1., 8., 9., 0., 7., 7.],
       [9., 0., 9., 5., 3., 5., 5., 3.]])]


In [86]:
a = np.arange(12)
b=a
print(b is a)
b.shape=3,4
print(a.shape)
print(id(a))
print(id(b))

True
(3, 4)
139980250127616
139980250127616


In [90]:
c=a.view()
print(c is a)
c.shape=2,6
print(a.shape)
c[0,4]=1234
print(a)
print(id(a))
print(id(c))

False
(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
139980250127616
139980249296944


In [91]:
d=a.copy()
print(d is a)
d[0,0]=9999
print(d)
print(a)

False
[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


In [95]:
import numpy as np
data = np.sin(np.arange(20).reshape(5,4))
print(data)
ind = data.argmax(axis=0)
print(ind)
data_max= data[ind,range(data.shape[1])]
print(data_max)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[0.98935825 0.84147098 0.99060736 0.6569866 ]


In [98]:
a=np.arange(0,40,10)
print(a)
b=np.tile(a,(4,3))
print(b)

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]]


In [101]:
a= np.array([[4,3,5],[1,2,1]])
print(a)
print('--------')
b=np.sort(a,axis=1)
print(b)
print('--------')
a=np.array([4,3,1,2])
j=np.argsort(a)
print(a[j])

[[4 3 5]
 [1 2 1]]
--------
[[3 4 5]
 [1 1 2]]
--------
[1 2 3 4]
